# Generated by Django 5.2.4 on 2026-05-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_delivery_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('createdat', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'Courier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderCourierPreference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'OrderCourierPreference',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='deliveryaddress',
            options={'verbose_name': 'Delivery Address', 'verbose_name_plural': 'Delivery Addresses'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-createdat']},
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
